training_pipeline_config:
  pipeline_name: customer_segmentation_artifacts
  artifact_dir: artifact


data_ingestion_config:
  dataset_download_url: "https://github.com/sourav-dhar/datasets/blob/main/Online%20Retail_new.zip"
  raw_data_dir: raw_data
  ingested_data_dir: ingested_data

data_validation_config:
  schema_dir: config
  schema_file_name: schema.yaml
  train_data: train_data

