ColumnNames:
  Country: object
  CustomerID: int64
  Description: object
  InvoiceDate: object
  InvoiceNo: object
  Quantity: int64
  StockCode: object
  UnitPrice: float64
FileName: Online Retail.csv
NumberOfColumns: 8
